# Generated by Django 2.0 on 2018-01-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_bill', to='room_booking.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_amount', models.FloatField(null=True)),
                ('room_price', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('number_of_days', models.FloatField(null=True)),
                ('total_amount', models.FloatField(null=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='room_booking.Booking')),
            ],
        ),
    ]
