# Generated by Django 2.0 on 2018-01-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0004_auto_20180118_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
