# Generated by Django 2.0 on 2018-01-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0005_booking_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
