# Generated by Django 2.0 on 2018-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0006_auto_20180119_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalbill',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='additionalbill',
            name='qty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='additionalbill',
            name='tax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='additionalbill',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
