# Generated by Django 2.0 on 2018-01-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0008_auto_20180119_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
