# Generated by Django 2.0 on 2018-01-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0009_auto_20180119_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypes',
            name='tax',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtypes',
            name='price',
            field=models.FloatField(),
        ),
    ]
