# Generated by Django 2.0 on 2018-01-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0010_auto_20180122_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_bill', to='room_booking.Booking'),
        ),
    ]
