# Generated by Django 2.0 on 2018-01-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0011_auto_20180123_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('tax', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='additionalbill',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(default=919019802163, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='token_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtypes',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
