# Generated by Django 2.0 on 2018-01-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0012_auto_20180129_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
