# Generated by Django 2.0 on 2018-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0013_booking_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalbill',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
