# Generated by Django 2.0 on 2018-01-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0014_additionalbill_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
