# Generated by Django 2.0 on 2018-01-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0015_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
    ]
