# Generated by Django 2.0 on 2018-02-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0016_remove_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='additional_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='number_of_days',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='room_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='tax',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
