# Generated by Django 2.0 on 2018-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0017_auto_20180214_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalbill',
            name='qty',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='token_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
