# Generated by Django 2.0 on 2018-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0018_auto_20180214_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalbill',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='additionalbill',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='token_amount',
            field=models.FloatField(default=0),
        ),
    ]
