# Generated by Django 2.0 on 2018-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0019_auto_20180214_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
    ]
