# Generated by Django 2.0 on 2018-02-22 07:29

from django.db import migrations, models
import enumchoicefield.fields
import room_booking.models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0022_auto_20180221_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='id_proof',
            new_name='id_proof_one',
        ),
        migrations.AddField(
            model_name='billing',
            name='paid_by',
            field=enumchoicefield.fields.EnumChoiceField(default=room_booking.models.PaidBy(2), enum_class=room_booking.models.PaidBy, max_length=4),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=enumchoicefield.fields.EnumChoiceField(default=room_booking.models.Status(2), enum_class=room_booking.models.Status, max_length=11),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_proof_two',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=enumchoicefield.fields.EnumChoiceField(default=room_booking.models.Status(1), enum_class=room_booking.models.Status, max_length=11),
        ),
    ]
