# Generated by Django 2.0 on 2018-02-23 11:32

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import room_booking.models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0023_auto_20180222_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('room_status', enumchoicefield.fields.EnumChoiceField(default=room_booking.models.Status(3), enum_class=room_booking.models.Status, max_length=11)),
                ('status', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='room_booking.Booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='room_booking.Rooms')),
            ],
        ),
    ]
