# Generated by Django 2.0 on 2018-02-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0024_roomstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
