# Generated by Django 2.0 on 2018-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0025_auto_20180223_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='room_price_total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
