# Generated by Django 2.0 on 2018-02-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0026_billing_room_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='invoice',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
