# Generated by Django 2.0 on 2018-03-30 15:53

from django.db import migrations
import django.db.models.deletion




def load_roletypes(apps, schema_editor):
    RoleTypes = apps.get_model("web_service", "RoleTypes")
    roleTypes_obj = RoleTypes(id=1, role_type='Admin')
    roleTypes_obj.save()

    roleTypes_obj = RoleTypes(id=2, role_type='Manager')
    roleTypes_obj.save()
    
    roleTypes_obj = RoleTypes(id=3, role_type='Employee')
    roleTypes_obj.save()


def delete_roletypes(apps, schema_editor):
    RoleTypes = apps.get_model("web_service", "RoleTypes")
    RoleTypes.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(load_roletypes,delete_roletypes),
    ]


