# Generated by Django 2.0 on 2017-12-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0002_auto_20171222_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_year', models.CharField(max_length=10)),
                ('crop_details', models.CharField(max_length=200)),
                ('crop_type', models.CharField(max_length=50)),
                ('pesticides', models.CharField(max_length=100)),
                ('deases', models.CharField(max_length=100)),
                ('chemicals', models.CharField(max_length=100)),
                ('fertilizer', models.CharField(max_length=200)),
                ('soil_test_report', models.CharField(max_length=1000)),
                ('water_test_report', models.CharField(max_length=1000)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivation_farmer_form', to='web_service.FarmerDetails')),
            ],
        ),
    ]
