# Generated by Django 2.0 on 2018-03-30 16:05

from django.db import migrations
import django.db.models.deletion


def load_departments(apps, schema_editor):
    Department = apps.get_model("web_service", "Department")
    department_obj = Department(id=1, name='Account')
    department_obj.save()

    department_obj = Department(id=2, name='Sales')
    department_obj.save()
    
    department_obj = Department(id=3, name='HR')
    department_obj.save()

    department_obj = Department(id=3, name='Reserch')
    department_obj.save()


def delete_departments(apps, schema_editor):
    Department = apps.get_model("web_service", "Department")
    Department.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0002_auto_20180330_1553'),
    ]

    operations = [
    	migrations.RunPython(load_departments,delete_departments),
    ]
