# Generated by Django 2.0 on 2017-12-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0004_auto_20171223_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200)),
                ('firm_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('safety_deposit_ammount', models.FloatField()),
                ('distributor_bank_account_number', models.CharField(max_length=30)),
                ('distributor_bank_name', models.CharField(max_length=100)),
                ('ifsc_or_rtgs', models.CharField(max_length=100)),
                ('branch_contact_number', models.CharField(max_length=15)),
                ('tin_number', models.CharField(max_length=100)),
                ('safety_check_one', models.CharField(max_length=100)),
                ('safety_check_two', models.CharField(max_length=100)),
                ('firm_status', models.CharField(max_length=20)),
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_father_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('dealer_address', models.CharField(max_length=500)),
                ('dealer_phone_number', models.CharField(max_length=15)),
                ('heir_guarantor', models.CharField(max_length=50)),
            ],
        ),
    ]
