# Generated by Django 2.0 on 2017-12-26 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0005_dealerform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivationform',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='farmer',
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivationform',
            name='activity',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='activity_cultivation', to='web_service.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_farmer', to='web_service.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleform',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_sample', to='web_service.Activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cultivationform',
            name='previous_year',
            field=models.DateField(),
        ),
    ]
