# Generated by Django 2.0 on 2017-12-27 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_service', '0006_auto_20171226_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivationform',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='sampleform',
            name='activity',
        ),
        migrations.AddField(
            model_name='cultivationform',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_cultivation', to='web_service.FarmerDetails'),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerdetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleform',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_sample', to='web_service.FarmerDetails'),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_farmer', to='web_service.Activity'),
        ),
    ]
