# Generated by Django 2.0 on 2017-12-27 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0007_auto_20171227_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationform',
            name='farmer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_cultivation', to='web_service.FarmerDetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_sample', to='web_service.FarmerDetails'),
        ),
    ]
