# Generated by Django 2.0 on 2017-12-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0010_farmerdetails_form_filled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedleave',
            name='appliedOn',
            field=models.DateField(auto_now_add=True),
        ),
    ]
