# Generated by Django 2.0 on 2018-01-03 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_service', '0012_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='actionOn',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='approvedOn',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='aproved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aproved_expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appliedleave',
            name='appliedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_leave', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cultivationform',
            name='chemicals',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cultivationform',
            name='crop_details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cultivationform',
            name='crop_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cultivationform',
            name='deases',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cultivationform',
            name='fertilizer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cultivationform',
            name='pesticides',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cultivationform',
            name='previous_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='photo_upload',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='sample',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='sample_given_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='sample_request',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='sample_request_qauntity',
            field=models.IntegerField(null=True),
        ),
    ]
