# Generated by Django 2.0 on 2018-01-05 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0014_sampleform_previous_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_address', models.CharField(max_length=500)),
                ('vendor_city', models.CharField(max_length=50)),
                ('vendor_pin_code', models.IntegerField()),
                ('vendor_pan', models.CharField(max_length=50)),
                ('vendor_gst', models.CharField(max_length=100)),
                ('vendor_contact', models.IntegerField()),
                ('vendor_po', models.CharField(max_length=100)),
                ('vendor_po_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='web_service.Activity'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_order', to='web_service.Vendors'),
            preserve_default=False,
        ),
    ]
