# Generated by Django 2.0 on 2018-01-05 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0015_auto_20180105_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='comfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendors',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
