# Generated by Django 2.0 on 2018-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0016_auto_20180105_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedleave',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
