# Generated by Django 2.0 on 2018-01-09 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0019_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100, null=True)),
                ('hsn_sac_code', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('uom', models.CharField(max_length=200, null=True)),
                ('rate', models.FloatField()),
                ('discount_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=200, null=True)),
                ('hsn_sac_code', models.CharField(max_length=200, null=True)),
                ('item_name', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('uom', models.CharField(max_length=200, null=True)),
                ('qty', models.FloatField()),
                ('discount_amount', models.FloatField()),
                ('rate', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='comfirmed',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='hsn_sac_code',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='vendor_po',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='vendor_po_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='comfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='po',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='po_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='shipping_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='vendor_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_gst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_pan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_shipping_address', to='web_service.Vendors'),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='web_service.Orders'),
        ),
    ]
