# Generated by Django 2.0 on 2018-01-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0020_auto_20180109_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='discount_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='qty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='discount_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
