# Generated by Django 2.0 on 2018-01-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0021_auto_20180109_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='po',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
