# Generated by Django 2.0 on 2018-01-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0022_auto_20180110_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerform',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='branch_contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='branch_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='dealer_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='dealer_father_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='dealer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='dealer_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='distributor_bank_account_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='distributor_bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='firm_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='firm_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='heir_guarantor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='ifsc_or_rtgs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='safety_check_one',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='safety_check_two',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealerform',
            name='tin_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmercroptype',
            name='crop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmersoiltype',
            name='soil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='reason',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='web_service.Orders'),
        ),
    ]
