# Generated by Django 2.0 on 2018-01-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0024_auto_20180110_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedleave',
            name='leave_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedleave',
            name='to_leave',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='land_area',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='secondary_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='soil_color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_pin_code',
            field=models.IntegerField(null=True),
        ),
    ]
