# Generated by Django 2.0 on 2018-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0025_auto_20180110_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
