# Generated by Django 2.0 on 2018-01-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0026_auto_20180112_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleform',
            name='excepted_result_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sampleform',
            name='sample_given_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
