# Generated by Django 2.0 on 2018-01-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0028_auto_20180113_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetails',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerdetails',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
