# Generated by Django 2.0 on 2018-01-25 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_service', '0032_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='salary',
            new_name='basic',
        ),
        migrations.AddField(
            model_name='salary',
            name='conveyance_allowance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='hra',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='misc_allowance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='proffesional_tax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='balance_casual_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='balance_compoff_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='balance_earned_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='balance_sick_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='lop',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='total_casual_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='total_compoff_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='total_earned_leave',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='total_sick_leave',
            field=models.FloatField(),
        ),
    ]
