# Generated by Django 2.0 on 2018-01-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0033_auto_20180125_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='net_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='net_salary_anum',
            field=models.FloatField(null=True),
        ),
    ]
