# Generated by Django 2.0 on 2018-01-29 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_service', '0034_auto_20180129_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedOn', models.DateField(auto_now_add=True)),
                ('count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='lop',
            new_name='total_lop',
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='basic',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='conveyance_allowance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='deduction',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='hra',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='misc_allowance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='net_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='net_salary_paybale',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='proffesional_tax',
            field=models.FloatField(null=True),
        ),
    ]
