# Generated by Django 2.0 on 2018-01-29 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_service', '0035_auto_20180129_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ducument_file', models.FileField(blank=True, null=True, upload_to='')),
                ('document_description', models.CharField(blank=True, max_length=200, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
