# Generated by Django 2.0 on 2018-01-30 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_service', '0036_employeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=20)),
                ('bank_address', models.CharField(max_length=200)),
                ('phone_no', models.CharField(blank=True, max_length=13, null=True)),
                ('bmicr_code', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_bank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
