# Generated by Django 2.0 on 2018-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0041_auto_20180201_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrequest',
            name='credited',
            field=models.BooleanField(default=False),
        ),
    ]
