# Generated by Django 2.0 on 2018-02-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0043_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelop',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
