# Generated by Django 2.0 on 2018-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0044_employeelop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrequest',
            name='credited_on',
            field=models.DateTimeField(null=True),
        ),
    ]
