# Generated by Django 2.0 on 2018-03-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0045_salaryrequest_credited_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrequest',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryrequest',
            name='salary_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
