# Generated by Django 2.0 on 2018-03-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0046_auto_20180316_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryrequest',
            old_name='salary',
            new_name='salary_year',
        ),
    ]
