# Generated by Django 2.0 on 2018-03-21 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_service', '0047_auto_20180316_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_qoute', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_qoute', models.CharField(blank=True, max_length=200, null=True)),
                ('manager_rating', models.FloatField(default=0, null=True)),
                ('self_rating', models.FloatField(default=0, null=True)),
                ('summary', models.CharField(default=0, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='appraisals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
