# Generated by Django 2.0 on 2018-03-21 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0048_appraisals'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisals',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisals',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
