# Generated by Django 2.0 on 2018-03-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0049_auto_20180321_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
