# Generated by Django 2.0 on 2018-03-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0050_auto_20180322_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisals',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
