# Generated by Django 2.0 on 2018-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0051_appraisals_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisals',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
