# Generated by Django 2.0 on 2018-03-28 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0052_auto_20180326_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedleave',
            name='appliedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_leave', to=settings.AUTH_USER_MODEL),
        ),
    ]
