# Generated by Django 2.0 on 2018-03-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_service', '0053_auto_20180328_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='account_number',
            field=models.CharField(default='123456789', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaves',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assigned_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
